# Generated by Django 2.1.5 on 2019-02-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190208_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localuser',
            name='email',
            field=models.EmailField(help_text='Required, a confirmation message will be sent to this address.', max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='localuser',
            name='jid',
            field=models.CharField(help_text='Required, a confirmation message will be sent to this address.', max_length=128, unique=True),
        ),
    ]
