# Generated by Django 2.1.5 on 2019-02-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190209_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localuser',
            name='jid',
            field=models.CharField(help_text='Required, a confirmation message will be sent to this address.', max_length=128, unique=True, verbose_name='JID'),
        ),
    ]
