# Generated by Django 2.1.5 on 2019-03-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190209_0725'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='localuser',
            managers=[
            ],
        ),
    ]
