# Generated by Django 2.1.5 on 2019-02-08 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20150515_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(50, 'CRITICAL'), (40, 'ERROR'), (30, 'WARNING'), (20, 'INFO'), (10, 'DEBUG')]),
        ),
        migrations.AlterField(
            model_name='server',
            name='ca',
            field=models.ForeignKey(blank=True, help_text='The Certificate Authority of the certificate used in SSL/TLS connections.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servers', to='server.CertificateAuthority', verbose_name='CA'),
        ),
        migrations.AlterField(
            model_name='server',
            name='city',
            field=models.CharField(blank=True, default='', help_text='City the server is located in.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='contact',
            field=models.CharField(help_text='The address where the server-admins can be reached.', max_length=60),
        ),
        migrations.AlterField(
            model_name='server',
            name='contact_name',
            field=models.CharField(blank=True, help_text='If you want to display a custom link-text for your contact details, give it here.', max_length=60),
        ),
        migrations.AlterField(
            model_name='server',
            name='contact_type',
            field=models.CharField(choices=[('M', 'MUC'), ('J', 'JID'), ('E', 'e-mail'), ('W', 'website')], default='J', help_text='What type your contact details are. This setting will affect how the contact details are rendered on the front page. If you choose a JID or an e-mail address, you will receive an automated confirmation message.', max_length=1),
        ),
        migrations.AlterField(
            model_name='server',
            name='country',
            field=models.CharField(blank=True, default='', help_text='Country the server is located in.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='domain',
            field=models.CharField(help_text='The primary domain of your server.', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='launched',
            field=models.DateField(help_text='When the server was launched.'),
        ),
        migrations.AlterField(
            model_name='server',
            name='moderation_message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='server',
            name='website',
            field=models.URLField(blank=True, help_text='A homepage where one can find information on your server. If left empty, the default is https://<domain>.'),
        ),
    ]
