# Generated by Django 2.1.5 on 2019-02-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20190208_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='policy_url',
            field=models.URLField(blank=True, default='', help_text='A URL describing any terms and conditions for using your server.', verbose_name='Policy URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='registration_url',
            field=models.URLField(blank=True, default='', help_text='A URL where users can create an account on your server.', verbose_name='Registration URL'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='website',
            field=models.URLField(blank=True, help_text='Homepage with information about your server. If left empty, the default is https://<domain>.'),
        ),
    ]
