# Generated by Django 2.1.5 on 2019-03-03 05:55

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_auto_20190216_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='launched_year',
            field=models.PositiveSmallIntegerField(default=server.models.launch_year_default, help_text='Year this server was launched.', validators=[server.models.launch_year_validator]),
        ),
    ]
