# Generated by Django 2.1.5 on 2019-03-03 05:44

from django.db import migrations


def set_year(apps, schema_editor):
    Server = apps.get_model('server', 'Server')
    for server in Server.objects.all():
        server.launched_year = server.launched.year
        server.save()


def rm_year(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_server_launched_year'),
    ]

    operations = [
        migrations.RunPython(set_year, rm_year),
    ]
