# Generated by Django 2.1.5 on 2019-03-03 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_auto_20190303_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='launched',
        ),
    ]
