# Generated by Django 2.1.5 on 2019-03-03 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_remove_server_launched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='launched_year',
            new_name='launched',
        ),
    ]
