# Generated by Django 2.1.5 on 2019-03-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_auto_20190303_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='contact_verified',
            field=models.BooleanField(default=False, help_text='If contact information is verified.'),
        ),
    ]
