# Generated by Django 2.1.5 on 2019-03-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_auto_20190303_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='city',
        ),
    ]
