# Generated by Django 2.1.5 on 2019-03-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0021_auto_20190309_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='moderated',
            field=models.BooleanField(default=None, help_text='If this server was manually moderated. "Unkown" = Was not yet moderated, "No" = Rejected.', null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='moderation_message',
            field=models.TextField(default='', help_text='Message that will be shown to user if server is rejected.'),
        ),
        migrations.AlterField(
            model_name='server',
            name='moderators_notified',
            field=models.BooleanField(default=False, help_text='If moderators have already been notified about this server.'),
        ),
    ]
