# Generated by Django 2.1.7 on 2019-03-13 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0023_auto_20190310_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='country_cc',
            field=models.CharField(default='DE', help_text='Two-letter country-code the server is located in.', max_length=2, verbose_name='Country Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='country',
            field=models.CharField(default='', help_text='Country the server is located in.', max_length=100),
            preserve_default=False,
        ),
    ]
