# Generated by Django 2.2 on 2019-04-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0024_auto_20190313_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='last_checked',
            field=models.DateTimeField(blank=True, help_text='When this server was last checked.', null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='last_seen',
            field=models.DateTimeField(blank=True, help_text='When this server was last seen online.', null=True),
        ),
    ]
